import { execFile } from 'node:child_process';
import { mkdir, mkdtemp, readFile, readdir, rm, stat, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { readWorks } from './works.js';
import { writeBrief } from './brief.js';
import { addSession } from './map.js';
import { writeMcpConfig } from './mcp-config.js';
import { writeWorkSettings } from './settings-file.js';
import { ensureStateDir, isDirectorySync, SHARED_STATE_IGNORE, stateDir, writeSelfIgnore } from './state-dir.js';
import { addBacklogItem } from './backlog.js';
import { prepareSharedIgnore, sharedProjectPaths, withSharedProjectLock } from './store.js';
import { createWork, readMap, updateMap, workPaths } from './store.js';

const run = promisify(execFile);
const git = (dir: string, ...args: string[]) => run('git', ['-C', dir, ...args]);

describe('stage 6 shared ignore policy', () => {
  it('upgrades only the exact old generated bytes, on a shared write rather than runtime ensure', async () => {
    const dir = path.join(project, '.parley'); await mkdir(dir);
    const file = path.join(dir, '.gitignore'); await writeFile(file, '*\n');
    await ensureStateDir(project); expect(await readFile(file, 'utf8')).toBe('*\n');
    await addBacklogItem(project, { title: 'Shared' });
    expect(await readFile(file, 'utf8')).toBe('*\n!.gitignore\n!backlog.md\n!plans/\n!plans/**\n!memory.md\n!decisions/\n!decisions/**\n!history-shared/\n!history-shared/**\n!recipes/\n!recipes/**\n');
  });
  it('новый каталог получает *, первая запись backlog переключает его на белый список; следующая запись файл не трогает', async () => {
    const file = path.join(project, '.parley', '.gitignore');
    await ensureStateDir(project);
    expect(await readFile(file, 'utf8')).toBe('*\n');
    await addBacklogItem(project, { title: 'First' });
    expect(await readFile(file, 'utf8')).toBe(SHARED_STATE_IGNORE);
    await addBacklogItem(project, { title: 'Second' });
    expect(await readFile(file, 'utf8')).toBe(SHARED_STATE_IGNORE);
  });
  it('новый каталог до shared-записи не показывается в git; после неё виден только белый список', async () => {
    await git(project, 'init', '-b', 'main');
    await ensureStateDir(project);
    expect((await git(project, 'status', '--porcelain', '-uall')).stdout).toBe('');
    await addBacklogItem(project, { title: 'Shared' });
    expect((await git(project, 'status', '--porcelain', '-uall')).stdout).toBe('?? .parley/.gitignore\n?? .parley/backlog.md\n');
  });
  it('написанный человеком .gitignore нового каталога не переписывается первой shared-записью', async () => {
    const dir = await ensureStateDir(project); const file = path.join(dir, '.gitignore');
    await writeFile(file, '*\n!mine\n'); await addBacklogItem(project, { title: 'Shared' });
    expect(await readFile(file, 'utf8')).toBe('*\n!mine\n');
  });
  it.each(['*\r\n', '\uFEFF*\n', '*\n\n', '*\n!mine\n', ''])('preserves custom signature %j', async text => {
    const dir = path.join(project, '.parley'); await mkdir(dir); const file = path.join(dir, '.gitignore');
    await writeFile(file, text); const result = await addBacklogItem(project, { title: 'Shared' });
    expect(await readFile(file, 'utf8')).toBe(text);
    expect(result.diagnostics).toContainEqual({ code: 'parley-gitignore-custom' });
  });
  it('preserves missing existing ignore and legacy priority, and never creates a replacement .parley', async () => {
    await mkdir(path.join(project, '.harnas'));
    const result = await addBacklogItem(project, { title: 'Legacy shared' });
    expect(result.diagnostics).toContainEqual({ code: 'parley-gitignore-custom' });
    expect(await exists(path.join(project, '.harnas', 'backlog.md'))).toBe(true);
    expect(await exists(path.join(project, '.harnas', '.gitignore'))).toBe(false);
    expect(await exists(path.join(project, '.parley'))).toBe(false);
  });
  it('keeps root ignores unchanged and reports the actual shared-path exclusion', async () => {
    await git(project, 'init', '-b', 'main');
    const file = path.join(project, '.gitignore'); await writeFile(file, '.parley/\n');
    const result = await addBacklogItem(project, { title: 'Local due to human ignore' });
    expect(result.diagnostics).toContainEqual({ code: 'parley-dir-ignored' });
    expect(await readFile(file, 'utf8')).toBe('.parley/\n');
  });
  it('stages only .gitignore/backlog/plans; local preferences, suggestions, descriptors and future runtime stay hidden', async () => {
    await git(project, 'init', '-b', 'main');
    await addBacklogItem(project, { title: 'Shared' });
    const dir = path.join(project, '.parley');
    for (const file of ['preferences.json', 'backlog-suggestions.json', 'backlog.lock', 'parley-md-receipt.json',
      'local/native-context/w-0001/s-01.json', 'works/w-0001/map.json', 'future-memory.json', 'plans/p-001.md']) {
      const target = path.join(dir, file); await mkdir(path.dirname(target), { recursive: true }); await writeFile(target, '{}');
    }
    await git(project, 'add', '-A');
    expect((await git(project, 'diff', '--cached', '--name-only')).stdout.trim().split('\n')).toEqual([
      '.parley/.gitignore', '.parley/backlog.md', '.parley/plans/p-001.md',
    ]);
  });
  it('exposes first-shared-write preparation for plan snapshots without changing runtime paths', async () => {
    const dir = path.join(project, '.parley'); await mkdir(dir); await writeFile(path.join(dir, '.gitignore'), '*\n');
    const paths = await sharedProjectPaths(project);
    expect(await withSharedProjectLock(paths, () => prepareSharedIgnore(paths))).toEqual([]);
    expect(workPaths(project, 'w-0001').dir).toBe(path.join(project, '.parley', 'works', 'w-0001'));
  });
});

let home = '';
let project = '';

beforeEach(async () => {
  home = await mkdtemp(path.join(tmpdir(), 'parley-home-'));
  project = await mkdtemp(path.join(tmpdir(), 'parley-project-'));
  process.env.PARLEY_HOME = home;
});

afterEach(async () => {
  delete process.env.PARLEY_HOME;
  await Promise.all([home, project].map((dir) => rm(dir, { recursive: true, force: true })));
});

const exists = async (target: string): Promise<boolean> =>
  stat(target).then(
    () => true,
    () => false,
  );

describe('stateDir — выбор каталога состояния проекта (R5)', () => {
  it('нет ни одного — новый .parley, и ничего не создаётся', async () => {
    expect(stateDir(project)).toBe(path.join(project, '.parley'));
    expect(await readdir(project)).toEqual([]);
  });

  it('есть только прежний .harnas — он', async () => {
    await mkdir(path.join(project, '.harnas'));
    expect(stateDir(project)).toBe(path.join(project, '.harnas'));
  });

  it('есть только .parley — он', async () => {
    await mkdir(path.join(project, '.parley'));
    expect(stateDir(project)).toBe(path.join(project, '.parley'));
  });

  it('есть оба — главнее .parley', async () => {
    await mkdir(path.join(project, '.parley'));
    await mkdir(path.join(project, '.harnas'));
    expect(stateDir(project)).toBe(path.join(project, '.parley'));
  });

  it('файл с именем .parley каталогом не считается: прежний .harnas остаётся', async () => {
    await writeFile(path.join(project, '.parley'), 'файл\n', 'utf8');
    await mkdir(path.join(project, '.harnas'));
    expect(stateDir(project)).toBe(path.join(project, '.harnas'));
  });

  it('символическая ссылка на каталог — каталог (проект, заведённый ссылкой, как раньше)', async () => {
    const target = path.join(project, 'elsewhere');
    await mkdir(target);
    await symlink(target, path.join(project, '.harnas'));
    expect(stateDir(project)).toBe(path.join(project, '.harnas'));
  });

  it('isDirectorySync: каталог — да; файл и отсутствующий путь — нет', async () => {
    await writeFile(path.join(project, 'f'), '', 'utf8');
    expect(isDirectorySync(project)).toBe(true);
    expect(isDirectorySync(path.join(project, 'f'))).toBe(false);
    expect(isDirectorySync(path.join(project, 'нет'))).toBe(false);
  });
});

describe('workPaths идёт за каталогом состояния', () => {
  it('в проекте без каталога состояния — .parley/works/<id>', () => {
    expect(workPaths(project, 'w-0001').dir).toBe(path.join(project, '.parley', 'works', 'w-0001'));
  });

  it('в проекте со старым .harnas — .harnas/works/<id>: тот же проект работает дальше', async () => {
    await mkdir(path.join(project, '.harnas'));
    const paths = workPaths(project, 'w-0001');
    expect(paths.dir).toBe(path.join(project, '.harnas', 'works', 'w-0001'));
    expect(paths.map).toBe(path.join(project, '.harnas', 'works', 'w-0001', 'map.json'));
    expect(paths.settings).toBe(path.join(project, '.harnas', 'works', 'w-0001', 'settings.json'));
  });
});

describe('ensureStateDir — каталог состояния сам прячет себя от git (R5)', () => {
  it('новый .parley получает .gitignore из одной строки *', async () => {
    const dir = await ensureStateDir(project);

    expect(dir).toBe(path.join(project, '.parley'));
    expect(await readFile(path.join(dir, '.gitignore'), 'utf8')).toBe('*\n');
  });

  it('повторный вызов .gitignore не переписывает', async () => {
    const dir = await ensureStateDir(project);
    await writeFile(path.join(dir, '.gitignore'), '*\n!keep\n', 'utf8');

    await ensureStateDir(project);
    expect(await readFile(path.join(dir, '.gitignore'), 'utf8')).toBe('*\n!keep\n');
  });

  it('уже существующий .parley не трогается: чужой .gitignore не появляется, прежнего не стирают', async () => {
    await mkdir(path.join(project, '.parley'));

    await ensureStateDir(project);
    expect(await exists(path.join(project, '.parley', '.gitignore'))).toBe(false);
  });

  it('прежний .harnas остаётся как есть: ни .gitignore, ни .parley', async () => {
    await mkdir(path.join(project, '.harnas'));

    const dir = await ensureStateDir(project);

    expect(dir).toBe(path.join(project, '.harnas'));
    expect(await readdir(project)).toEqual(['.harnas']);
    expect(await readdir(dir)).toEqual([]);
  });

  it('проекта ещё нет на диске — создаётся вместе с каталогом', async () => {
    const fresh = path.join(project, 'новый', 'проект');

    await ensureStateDir(fresh);

    expect(await readFile(path.join(fresh, '.parley', '.gitignore'), 'utf8')).toBe('*\n');
  });

  it('параллельные вызовы: один .gitignore из одной строки *', async () => {
    await Promise.all(Array.from({ length: 8 }, () => ensureStateDir(project)));

    expect(await readFile(path.join(project, '.parley', '.gitignore'), 'utf8')).toBe('*\n');
  });

  it('`.parley` — файл: вызов отказывает, а не молча пишет мимо', async () => {
    await writeFile(path.join(project, '.parley'), 'файл\n', 'utf8');

    await expect(ensureStateDir(project)).rejects.toThrow();
  });

  it('git не видит новый каталог совсем: и .gitignore, и runtime спрятаны строкой *', async () => {
    await run('git', ['init', '-b', 'main', project]);
    await git(project, 'config', 'user.email', 'тест@parley');
    await git(project, 'config', 'user.name', 'тест');
    await writeFile(path.join(project, 'a.txt'), 'a\n', 'utf8');
    await git(project, 'add', 'a.txt');
    await git(project, 'commit', '-m', 'первый');

    await createWork(project, { title: 'Авторизация' });

    expect((await git(project, 'status', '--porcelain', '-uall')).stdout).toBe('');
    await git(project, 'add', '-A');
    expect((await git(project, 'status', '--porcelain')).stdout).toBe('');
  });
});

describe('writeSelfIgnore — .gitignore из строки * в уже существующем каталоге (перенос .harnas → .parley, R6)', () => {
  it('кладёт .gitignore из строки *; лежащий не перезаписывает', async () => {
    const dir = path.join(project, '.parley');
    await mkdir(dir);

    await writeSelfIgnore(dir);
    expect(await readFile(path.join(dir, '.gitignore'), 'utf8')).toBe('*\n');

    await writeFile(path.join(dir, '.gitignore'), '*\n!keep\n', 'utf8');
    await writeSelfIgnore(dir);
    expect(await readFile(path.join(dir, '.gitignore'), 'utf8')).toBe('*\n!keep\n');
  });

  it('каталога нет — отказ, а не молчаливая запись мимо', async () => {
    await expect(writeSelfIgnore(path.join(project, '.parley'))).rejects.toThrow();
  });
});

describe('работа в проекте: новый и прежний каталог состояния', () => {
  it('createWork в проекте без каталога: .parley/works/w-0001 и .parley/.gitignore', async () => {
    await createWork(project, { title: 'Первая' });

    expect(await exists(path.join(project, '.parley', 'works', 'w-0001', 'map.json'))).toBe(true);
    expect(await readFile(path.join(project, '.parley', '.gitignore'), 'utf8')).toBe('*\n');
    expect(await exists(path.join(project, '.harnas'))).toBe(false);
  });

  it('createWork в проекте со старым .harnas: карта ложится туда, .parley не заводится', async () => {
    await mkdir(path.join(project, '.harnas'));

    const map = await createWork(project, { title: 'Первая' });

    expect(await exists(path.join(project, '.harnas', 'works', map.work.id, 'map.json'))).toBe(true);
    expect(await exists(path.join(project, '.parley'))).toBe(false);
    // Прежний каталог остаётся как был: своего .gitignore код в него не кладёт.
    expect(await exists(path.join(project, '.harnas', '.gitignore'))).toBe(false);
  });

  it('карты старого проекта читаются и пишутся на месте: updateMap, readMap, readWorks', async () => {
    await mkdir(path.join(project, '.harnas'));
    const created = await createWork(project, { title: 'Старая' });
    // Индекс потерян (перенос дома): список берётся с диска проекта.
    await rm(path.join(home, 'works-index.json'));

    await updateMap(project, created.work.id, (map) => {
      map.work.goal = 'цель';
    });

    expect((await readMap(project, created.work.id)).work.goal).toBe('цель');
    const listed = await readWorks(project);
    expect(listed.map((entry) => entry.map.work.id)).toEqual([created.work.id]);
    expect(await exists(path.join(project, '.parley'))).toBe(false);
  });

  it('при обоих каталогах главнее .parley (R5): карты прежнего не видны, пока их не перенесли, читатель их не сливает', async () => {
    await mkdir(path.join(project, '.harnas'));
    const old = await createWork(project, { title: 'Старая' });
    await mkdir(path.join(project, '.parley'));
    await rm(path.join(home, 'works-index.json'));

    expect((await readWorks(project)).map((entry) => entry.map.work.id)).toEqual([]);
    expect(await exists(path.join(project, '.harnas', 'works', old.work.id, 'map.json'))).toBe(true);
  });
});

describe('любая запись в каталог состояния, которого нет, заводит его вместе с .gitignore (R5)', () => {
  const selfIgnored = async (): Promise<void> => {
    expect(await readFile(path.join(project, '.parley', '.gitignore'), 'utf8')).toBe('*\n');
    expect(await exists(path.join(project, '.harnas'))).toBe(false);
  };

  it('конфиг MCP сессии', async () => {
    await writeMcpConfig(project, 'w-0042', 's-01');
    await selfIgnored();
  });

  it('файл настроек с хуками', async () => {
    await writeWorkSettings(project, 'w-0042');
    await selfIgnored();
  });

  it('бриф: каталог стёрли вместе с работой, а бриф пишут заново', async () => {
    await createWork(project, { title: 'Первая' });
    const map = await updateMap(project, 'w-0001', (current) => {
      addSession(current, { provider: 'claude', label: 'план', task: 'составить план' });
    });
    await rm(path.join(project, '.parley'), { recursive: true });

    await writeBrief(project, map, 's-01');

    await selfIgnored();
  });

  it('прежний .harnas и здесь остаётся единственным: .parley не заводится', async () => {
    await mkdir(path.join(project, '.harnas'));

    await writeMcpConfig(project, 'w-0042', 's-01');
    await writeWorkSettings(project, 'w-0042');

    expect(await exists(path.join(project, '.parley'))).toBe(false);
    expect(await exists(path.join(project, '.harnas', 'works', 'w-0042', 'mcp', 's-01.json'))).toBe(true);
  });
});

it('memory whitelist migrates only exact previous generated LF bytes on a write, never a read', async () => {
  const { PRE_MEMORY_STATE_IGNORE, SHARED_STATE_IGNORE } = await import('./state-dir.js');
  const { readProjectMemory, addProjectMemory } = await import('./project-memory.js');
  const dir = path.join(project, '.parley'); await mkdir(dir); const file = path.join(dir, '.gitignore');
  await writeFile(file, PRE_MEMORY_STATE_IGNORE); await readProjectMemory(project);
  expect(await readFile(file, 'utf8')).toBe(PRE_MEMORY_STATE_IGNORE);
  await addProjectMemory(project, { kind: 'fact', fact: 'Shared memory' });
  expect(await readFile(file, 'utf8')).toBe(SHARED_STATE_IGNORE);
  for (const custom of [PRE_MEMORY_STATE_IGNORE.replaceAll('\n', '\r\n'), `\uFEFF${PRE_MEMORY_STATE_IGNORE}`, '*\n!memory.md\n']) {
    await writeFile(file, custom); await addProjectMemory(project, { kind: 'fact', fact: `Other ${custom.length}` });
    expect(await readFile(file, 'utf8')).toBe(custom);
  }
});


it('journal/shared-history whitelist migrates exact generated generations only; local history remains ignored', async () => {
  const { PRE_JOURNAL_STATE_IGNORE, PRE_MEMORY_STATE_IGNORE, PRE_RECIPES_STATE_IGNORE, SHARED_STATE_IGNORE } = await import('./state-dir.js');
  const dir = path.join(project, '.parley'); await mkdir(dir); const file = path.join(dir, '.gitignore');
  const paths = await sharedProjectPaths(project);
  for (const generated of ['*\n', PRE_MEMORY_STATE_IGNORE, PRE_JOURNAL_STATE_IGNORE, PRE_RECIPES_STATE_IGNORE]) {
    await writeFile(file, generated);
    await withSharedProjectLock(paths, () => prepareSharedIgnore(paths));
    expect(await readFile(file, 'utf8')).toBe(SHARED_STATE_IGNORE);
  }
  for (const custom of [PRE_JOURNAL_STATE_IGNORE.replaceAll('\n', '\r\n'), `\uFEFF${PRE_JOURNAL_STATE_IGNORE}`, `${PRE_JOURNAL_STATE_IGNORE}!human-file\n`]) {
    await writeFile(file, custom); await withSharedProjectLock(paths, () => prepareSharedIgnore(paths));
    expect(await readFile(file, 'utf8')).toBe(custom);
  }
  // Рецепты проекта живут в git: белый список открывает `recipes/`.
  expect(SHARED_STATE_IGNORE).toContain('!recipes/\n!recipes/**\n');
  for (const custom of [PRE_RECIPES_STATE_IGNORE.replaceAll('\n', '\r\n'), `\uFEFF${PRE_RECIPES_STATE_IGNORE}`, `${PRE_RECIPES_STATE_IGNORE}!human-file\n`]) {
    await writeFile(file, custom); await withSharedProjectLock(paths, () => prepareSharedIgnore(paths));
    expect(await readFile(file, 'utf8')).toBe(custom);
  }
  expect(SHARED_STATE_IGNORE).not.toContain('!history/');
});
